# Generated by Django 6.0.3 on 2026-03-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0003_customuser_subscribed_articles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
